### PR TITLE
#1 Fix issue with boolean parsing

### PR DESCRIPTION
**Pull request by DominicWatson**
Do not assume anything that passes CF's IsBoolean() is a YAML boolean. This would cover things like numbers and "yes" & "no" which should not be treated as a boolean in YAML.

### CODE REVIEW

**Comment by elpete** [comment]
Hmm...this definitely needs to change.  I recently was trying to fix this [over in qb.](https://github.com/coldbox-modules/qb/commit/8237afeb913d878c7d82233b052110759d47a7dc)  I don't think this goes far enough since `0 == false` and `1 == true` in CFML, as well as `"no" == "false"` and `"yes" == "true"`.  We could use the trick to check the underlying Java class, but this leaves CF2016 out in the cold.

**Comment by DominicWatson** [comment]
In YAML though, boolean is either "true" or "false" right? So this fix should be universal? i.e. if the YAML says:

```yaml
retryCount: 1
```

It should never be assumed to be `retryCount: true`

**Comment by elpete** [comment]
I agree with what you are saying.  However, the fix you have parses the following:
```yml
notifications:
  email: false
  testOne: "no"
  testTwo: 0
```
As
```json
{
  "notifications": {
    "email": false,
    "testOne": false,
    "testTwo": false
  }
}
```

**Comment by elpete** [comment]
This `if` check will solve it on CF2018 and Lucee 5:
```cfc
if ( arguments.map.getClass().getSimpleName() == "Boolean" ) {
    return javacast( "boolean", arguments.map );
}
```

**Comment by DominicWatson** [comment]
Right, yes - damned CF. Can use a string function instead for all engine compatibility if that works with you? (have amended)

**Comment by elpete** [comment]
That's a clever fix.  Thanks!

**Pull request merged**
